PAGING_ITEM_NUMBER = 10
DEFAULT_TIMEOUT = 20

# Gitlab keys
GITLAB_HOST_NAME = "GITLAB_HOST_NAME"
GITLAB_PRIVATE_TOKEN = "GITLAB_PRIVATE_TOKEN"
GITLAB_KEY_LIST = (GITLAB_HOST_NAME, GITLAB_PRIVATE_TOKEN)
