APP_NAME = "git_search_command"


class GitLabConstant:
    NAME = "GitLab"
    GROUP_API_LIMIT = 10
    SEARCH_API_LIMIT = 100
    SEARCH_RATE_LIMIT_CALLS = 60
    SEARCH_RATE_LIMIT_PERIOD = 60


class GitHubConstant:
    NAME = "GitHub"
    REPOSITORY_LIST_API_LIMIT = 10
    SEARCH_API_LIMIT = 100
    SEARCH_RATE_LIMIT_CALLS = 30
    SEARCH_RATE_LIMIT_PERIOD = 60
