name: Push & Pull Request

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9']
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      id: setup-python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip pre-commit
    - name: Load cached hooks of pre-commit
      id: cached-pre-commit
      uses: actions/cache@v3
      with:
        path: ~/.cache/pre-commit
        key: ${{ runner.os }}-pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
    - name: Run pre-commit
      run: |
        pre-commit run --verbose --all-files --show-diff-on-failure
